In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print (type(a), a.shape, a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [3]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

(2, 3)
1 2 4


In [13]:
c = np.array([[[1,2,3], [4,5,6], [19,20,21]], [[7,8,9], [10,11,12], [22,23,24]], [[13,14,15], [16,17,18], [25,26,27]]])
print(c)
print(c.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [19 20 21]]

 [[ 7  8  9]
  [10 11 12]
  [22 23 24]]

 [[13 14 15]
  [16 17 18]
  [25 26 27]]]
(3, 3, 3)


In [23]:
d = np.zeros((2,4,3))
print(d)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [22]:
e = np.ones((1,2), dtype=int)
print(e)

[[1 1]]


In [21]:
f = np.full((2,2), 7)
print(f)

[[7 7]
 [7 7]]


In [29]:
g = np.eye(10)
print(g)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [25]:
h = np.random.random((2,2))
print(h)

[[0.93863027 0.16602529]
 [0.23626118 0.96519708]]


In [36]:
a=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (a)

b = a[0:2, 1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [40]:
print (a[0,1])
b[0,0] = 77
print(a[0,1])
print(b)

2
2
[[77  3]
 [ 6  7]]


In [38]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)
bool_idx = (a>2)

print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [39]:
print(a[bool_idx])
print(a[a>2])

[3 4 5 6]
[3 4 5 6]


In [41]:
x = np.array([1,2])
y = np.array([1.0,2.0])
z = np.array([1,2], dtype = np.int64)

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


In [42]:
x = np.array([[1,2], [3,4]], dtype=np.float)
y = np.array([[5,6], [7,8]], dtype=np.float64)
print (x.dtype)

print(x+y)
print(np.add(x,y))

float64
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [44]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [45]:
print(x*y)
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [46]:
print (x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [49]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [51]:
v = np.array([9,10])
w = np.array([11,12])

print(v.dot(w))
print(np.dot(v,w))

219
219


In [53]:
x=np.array([[1,2], [3,4]])

print(x)
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [54]:
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [55]:
v=np.array([[1,2,3]])
print(v)
print(v.T)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [56]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x)

for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [57]:
vv = np.tile(v, (4,1))
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [58]:
y = x+vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [59]:
print(x)
print(v)
y = x+v
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
